### ISSUE TITLE
IAPDUParser

### ISSUE THREAD

**Issue by zhangyoumeng** [qinling0918/FrameMessageParser#1]
你好，最近在学习698协议，看到你的代码，IAPDUParser类没有找到，能否提供学习呢？

**Comment by qinling0918** [comment]
IAPDUParser类是解析链路层数据时才会用到的，水平有限，目前链路层数据解析只实现了一点。所以并没有提交。另外可能关于frame698类分帧格式域进制转换有些问题，我会抽空修复一下！

**Comment by zhangyoumeng** [comment]
你好，能否提供一下解析链路层思路，一起完成，做一个通用的解析库。

**Comment by qinling0918** [comment]
去瞅瞅Frame库吧。我目前就写了这么多。

**Comment by qinling0918** [comment]
时隔一年，实现添加了698报文 数据域的解析，不过由于698协议比较复杂，仅支持了不足协议中一半不到的数据项的解析。仅支持了 Get、Set、Action操作类的部分解析，若有其他需求，可参考本项目中的解析方案进行拓展。
